## Basic functions testing from quadratic.py

In [1]:
import numpy as np

In [2]:
from quadratic import *

In [3]:
x = np.random.rand(16,16,16).astype(np.float32)
b = np.random.rand(16,16,16).astype(np.float32)

In [4]:
h = np.float32(1./16)

In [5]:
C2 = np.float32(0.2)
C4 = np.float32(0.1)
alphaB = np.float32(0.1)
alphaM = np.float32(0.3)
H = np.float32(1.)
a = np.float32(1.)
M = np.float32(1.)

In [6]:
res = operator(x,b,h,C2,C4,alphaB,alphaM,H,a,M)

In [7]:
ix = np.int32(1)
iy = ix
iz = ix

s1 = solution_quadratic_equation(x,b[ix,iy,iz],ix,iy,iz,h,C2,C4,alphaB,alphaM,H,a,M)

In [8]:
s1

0.596568763256073

In [9]:
xo = np.copy(x)

In [10]:
jacobi(x,b,h,C2,C4,alphaB,alphaM,H,a,M)

In [11]:
smoothing(xo,b,h,C2,C4,alphaB,alphaM,H,a,M,6)

In [12]:
xo

array([[[1.0159538 , 1.0376018 , 1.054323  , ..., 1.0689801 ,
         1.0707806 , 1.0004863 ],
        [1.0225244 , 1.0446328 , 1.0622169 , ..., 1.0659814 ,
         1.0712969 , 1.0036833 ],
        [1.02808   , 1.0488712 , 1.0647678 , ..., 1.06213   ,
         1.0723403 , 1.0084254 ],
        ...,
        [1.0694326 , 1.081766  , 1.0875713 , ..., 1.1152264 ,
         1.1251762 , 1.0548631 ],
        [1.0772971 , 1.0917014 , 1.1005961 , ..., 1.1256031 ,
         1.1340237 , 1.0635513 ],
        [1.0080252 , 1.027671  , 1.0422418 , ..., 1.0626982 ,
         1.0656888 , 0.9946963 ]],

       [[1.0347762 , 1.0498903 , 1.0647076 , ..., 1.0884922 ,
         1.092205  , 1.0232016 ],
        [1.0359272 , 1.0539365 , 1.0716732 , ..., 1.0829313 ,
         1.0893506 , 1.0215188 ],
        [1.0348134 , 1.0531515 , 1.0690454 , ..., 1.0758237 ,
         1.0855033 , 1.0200428 ],
        ...,
        [1.0819156 , 1.087633  , 1.0908031 , ..., 1.1340646 ,
         1.1444575 , 1.0738577 ],
        [1.0

In [13]:
smoothing(xo,b,h,C2,C4,alphaB,alphaM,H,a,M,6)

In [14]:
xo

array([[[1.51646  , 1.5293015, 1.5379088, ..., 1.565988 , 1.5790473,
         1.5019006],
        [1.5221701, 1.5352731, 1.5438478, ..., 1.5713122, 1.5842962,
         1.507192 ],
        [1.5259612, 1.5389106, 1.5473132, ..., 1.57535  , 1.5882149,
         1.5109271],
        ...,
        [1.582018 , 1.5922978, 1.5997967, ..., 1.635401 , 1.6496521,
         1.5697236],
        [1.5906371, 1.6016508, 1.6094445, ..., 1.643808 , 1.657653 ,
         1.5777106],
        [1.5084704, 1.5206102, 1.528996 , ..., 1.5589355, 1.5721589,
         1.4946926]],

       [[1.5287266, 1.5401728, 1.5481044, ..., 1.5815368, 1.5938127,
         1.5159193],
        [1.5325515, 1.5447329, 1.5531917, ..., 1.5853492, 1.5972308,
         1.5190597],
        [1.5343289, 1.5470479, 1.556024 , ..., 1.5871077, 1.5988019,
         1.5202266],
        ...,
        [1.593716 , 1.603193 , 1.6103699, ..., 1.649379 , 1.6630946,
         1.5825589],
        [1.6034409, 1.6132876, 1.6204097, ..., 1.6590571, 1.6723608,
   

In [15]:
xn = np.random.rand(16,16,16).astype(np.float32)

In [16]:

res1 = residual(xn,b,h,C2,C4,alphaB,alphaM,H,a,M)

In [17]:
op1 = operator(xn,b,h,C2,C4,alphaB,alphaM,H,a,M)

In [18]:
res1[0,0,0]

-859.05853

In [19]:
op1[0,0,0]

859.05853

In [20]:
reserr = residual_error(xn,b,h,C2,C4,alphaB,alphaM,H,a,M)

In [21]:
reserr

334405.75

In [22]:
terr = truncation_error(xn,b,h,C2,C4,alphaB,alphaM,H,a,M)

In [23]:
terr

79485.75

In [25]:
phi0 = initialise_potential(b,h,C2,alphaB,alphaM,a,M)

In [26]:
phi0

array([[[-3.14360630e-04, -3.98655393e-04, -3.13039083e-04, ...,
         -3.40610277e-04, -9.39068923e-05, -4.37979215e-05],
        [-2.46582873e-04, -4.24688333e-04, -3.88286106e-04, ...,
         -2.83961144e-05, -2.80011416e-04, -1.60826734e-04],
        [-5.65444279e-05, -2.00757218e-04, -2.36356369e-04, ...,
         -1.17547752e-04, -7.74524960e-05, -1.02697937e-04],
        ...,
        [-1.82913354e-04, -2.02446143e-04, -3.97964235e-04, ...,
         -2.07170699e-04, -2.30238526e-04, -1.82500924e-04],
        [-4.30655316e-04, -2.55116262e-04, -7.70488623e-05, ...,
         -3.11201817e-04, -1.54897803e-04, -3.28888622e-04],
        [-2.14818268e-04, -2.94344674e-04, -3.61235172e-04, ...,
         -3.66624095e-04, -3.08736344e-04, -1.67308797e-04]],

       [[-3.11168958e-04, -2.66370480e-04, -7.77180539e-05, ...,
         -2.93892575e-04, -3.51389230e-04, -3.23399669e-04],
        [-4.35457696e-05, -1.90863488e-04, -1.85480952e-04, ...,
         -4.25933569e-04, -2.18197601e

## Additional field testing

In [3]:
import pandas as pd
import cosmotable
import utils

In [5]:
param = pd.Series({
    "theory": "eft",
    "alphaB0": 0.1,
    "alphaM0": 0.3,
    "H0": 70.0,
    "Om_m": 0.3,
    "T_cmb": 2.726,
    "N_eff": 3.044,
    "w0": -1.0,
    "wa": 0.0,
    "base": "./",
    "extra": "test",
    "aexp":1,
    "boxlen":100,
    "npart":256**3,
    "compute_additional_field":True,
    "ncoarse":8,
    "Npre":4,
    "Npost":1
    })

In [6]:
tables = cosmotable.generate(param)
utils.set_units(param)

/opt/anaconda3/lib/python3.12/site-packages/astropy/cosmology/flrw/w0wacdm.py:195: RuntimeWarning: invalid value encountered in scalar divide
  return zp1 ** (3 * (1 + self._w0 + self._wa)) * exp(-3 * self._wa * z / zp1)


In [7]:
param

theory                                                              eft
alphaB0                                                             0.1
alphaM0                                                             0.3
H0                                                                 70.0
Om_m                                                                0.3
T_cmb                                                             2.726
N_eff                                                             3.044
w0                                                                 -1.0
wa                                                                  0.0
base                                                                 ./
extra                                                              test
aexp                                                                  1
boxlen                                                              100
npart                                                          1

In [8]:
import eftcalcs

In [9]:
eft_quantities = eftcalcs.geteft(param,tables)

In [11]:
potential = np.empty(0, dtype=np.float32)
density = np.random.rand(256,256,256).astype(np.float32)
h = 1./256

param["alphaB"] = eft_quantities[0]
param["alphaM"] = eft_quantities[1]
param["C2"] = eft_quantities[2]
param["C4"] = eft_quantities[3]
param["H"] = eft_quantities[4]
param["M"] = eft_quantities[5]

In [12]:
import solver

In [13]:
phi = solver.initialise_potential(potential,density,h,param,tables)

In [14]:
phi = solver.get_additional_field(phi,density,h,param,tables)

[0.09999999999999999, 0.3, 1.1930805152998332, 0.2, 0.9999999999999999, 0.9672311250534926]
Mean chi: -1.1889e-07, dens: -5.0008e-01, stdev: 2.8867e-01


### initialise_potential and get_additional_field work: 13 Jan 25

In [15]:
phi.shape

(256, 256, 256)

In [16]:
phi

array([[[5.5342894, 5.6336546, 5.19891  , ..., 6.147012 , 6.11988  ,
         6.0098987],
        [5.6537414, 5.092778 , 5.353097 , ..., 5.850599 , 6.1431775,
         5.6639237],
        [5.248065 , 5.374729 , 4.796589 , ..., 5.974196 , 5.9496946,
         5.862096 ],
        ...,
        [6.1031866, 5.807668 , 5.915957 , ..., 6.271494 , 6.276466 ,
         6.179034 ],
        [6.0842505, 6.10483  , 5.8928285, ..., 6.2689257, 6.309392 ,
         6.216492 ],
        [5.9805923, 5.6208787, 5.81822  , ..., 6.182949 , 6.228507 ,
         6.043983 ]],

       [[5.6725187, 5.1277094, 5.374758 , ..., 5.8716035, 6.152758 ,
         5.6850777],
        [5.158463 , 5.3130817, 4.690976 , ..., 5.9311304, 5.9227495,
         5.8358417],
        [5.4143534, 4.7166576, 5.0117497, ..., 5.5637836, 6.032942 ,
         5.414269 ],
        ...,
        [5.846963 , 5.8738756, 5.5054445, ..., 6.219547 , 6.2400045,
         6.142364 ],
        [6.1271124, 5.873553 , 5.9857216, ..., 6.232169 , 6.2284813,
   